Repository Laundry-Platform/Laundry_Core, pull requests merged in 2022-06, with the labels that each got.

#9 Feature/mybatis configuration
  build.gradle
  src/main/java/com/coders/laundry/configuration/MyBatisConfig.java
  src/main/java/com/coders/laundry/controller/HomeController.java
  src/main/java/com/coders/laundry/domain/entity/MemberEntity.java
  src/main/java/com/coders/laundry/repository/HomeRepository.java
  src/main/java/com/coders/laundry/service/HomeService.java
  src/main/resources/mapper/homeMapper.xml
  src/main/resources/templates/home.html
Labels: orm

#13 Feature/h2 web console allow others
  src/main/resources/application.yml
Labels: db

#19 Feature/pull request template
  .github/pull_request_template.md
  .gitignore
Labels: documentation

#20 Feature/member domain schema
  src/main/resources/db/h2/dev/schema.sql
Labels: db

#33 Feature/laundry sample data refactoring
  build.gradle
  src/main/java/com/coders/laundry/LaundryApplication.java
  src/main/java/com/coders/laundry/data/DataCreator.java
  src/main/java/com/coders/laundry/data/open/OpenLaundryData.java
  src/main/java/com/coders/laundry/jackson/StringLowerCaseDeserializer.java
  src/main/java/com/coders/laundry/util/StringUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/data/laundry.json
  src/main/resources/data/laundry2.json
Labels: refactoring

#17 Feature/board CRUD
  src/main/java/com/coders/laundry/controller/BoardController.java
  src/main/java/com/coders/laundry/domain/entity/CategoryEntity.java
  src/main/java/com/coders/laundry/domain/entity/CommentEntity.java
  src/main/java/com/coders/laundry/domain/entity/PostEntity.java
  src/main/java/com/coders/laundry/domain/entity/ReplyEntity.java
  src/main/java/com/coders/laundry/domain/entity/ReviewEntity.java
  src/main/java/com/coders/laundry/dto/CategoryDTO.java
  src/main/java/com/coders/laundry/dto/CommentDTO.java
  src/main/java/com/coders/laundry/dto/PostDTO.java
  src/main/java/com/coders/laundry/dto/ReplyDTO.java
  src/main/java/com/coders/laundry/dto/ReviewDTO.java
  src/main/java/com/coders/laundry/repository/BoardRepository.java
  src/main/java/com/coders/laundry/service/BoardService.java
  src/main/resources/db/h2/dev/schema.sql
  src/main/resources/mapper/boardMapper.xml
  src/test/java/com/coders/laundry/service/BoardServiceTest.java
Labels: db, reviewing, developing

#32 Feature/laundry crud
  src/main/java/com/coders/laundry/domain/entity/LaundryEntity.java
  src/main/java/com/coders/laundry/repository/LaundryRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/db/h2/dev/data-laundry.sql
  src/main/resources/db/h2/dev/schema-laundry.sql
  src/main/resources/mapper/laundryMapper.xml
  src/test/java/com/coders/laundry/repository/LaundryRepositoryTest.java
Labels: test, orm

#35 Refactor/h2 schema file
  src/main/resources/db/h2/dev/data-member.sql
  src/main/resources/db/h2/dev/schema-community.sql
  src/main/resources/db/h2/dev/schema-member.sql
  src/main/resources/db/h2/dev/schema.sql
  src/main/resources/mapper/laundryMapper.xml
Labels: db, simple, refactoring

#44 Refactoring SQL File
  src/main/resources/db/h2/dev/data-community.sql
  src/main/resources/db/h2/dev/schema-community.sql
Labels: simple, refactoring

#48 Feature/laundry visit history
  src/main/java/com/coders/laundry/domain/entity/LaundryVisitHistoryEntity.java
  src/main/java/com/coders/laundry/repository/LaundryVisitHistoryRepository.java
  src/main/resources/db/h2/dev/data-member.sql
  src/main/resources/mapper/laundryVisitHistoryMapper.xml
  src/test/java/com/coders/laundry/repository/LaundryVisitHistoryRepositoryTest.java
Labels: enhancement, db
