Repository Laundry-Platform/Laundry_Core, pull requests merged in 2022-07, with the labels that each got.

#40 Feature/member crud
  src/main/java/com/coders/laundry/domain/entity/MemberEntity.java
  src/main/java/com/coders/laundry/repository/MemberRepository.java
  src/main/resources/mapper/MemberMapper.xml
  src/test/java/com/coders/laundry/repository/MemberRepositoryTest.java
Labels: enhancement, db, orm

#47 Feature/like crud
  src/main/java/com/coders/laundry/domain/entity/LaundryLikeEntity.java
  src/main/java/com/coders/laundry/repository/LaundryLikeRepository.java
  src/main/resources/db/h2/dev/data-member.sql
  src/main/resources/db/h2/dev/schema-member.sql
  src/main/resources/mapper/laundryLikeMapper.xml
  src/test/java/com/coders/laundry/repository/LaundryLikeRepositoryTest.java
Labels: enhancement, db

#65 Bugfix/board select query
  src/main/resources/mapper/boardMapper.xml
Labels: hotfix

#64 Feature/search history crud
  src/main/java/com/coders/laundry/domain/entity/SearchHistoryEntity.java
  src/main/java/com/coders/laundry/repository/SearchHistoryRepository.java
  src/main/resources/db/h2/dev/data-search.sql
  src/main/resources/db/h2/dev/schema-search.sql
  src/main/resources/mapper/searchHistoryMapper.xml
  src/test/java/com/coders/laundry/repository/SearchHistoryRepositoryTest.java
Labels: enhancement, db, orm

#66 Feature/recent search history
  src/main/java/com/coders/laundry/controller/SearchHistoryController.java
  src/main/java/com/coders/laundry/domain/exceptions/NotAuthorizedException.java
  src/main/java/com/coders/laundry/dto/ErrorResponse.java
  src/main/java/com/coders/laundry/dto/Page.java
  src/main/java/com/coders/laundry/dto/Pageable.java
  src/main/java/com/coders/laundry/dto/SearchHistory.java
  src/main/java/com/coders/laundry/dto/SearchHistoryRegisterRequest.java
  src/main/java/com/coders/laundry/dto/SearchHistoryRemoveRequest.java
  src/main/java/com/coders/laundry/repository/SearchHistoryRepository.java
  src/main/java/com/coders/laundry/service/SearchHistoryService.java
  src/main/java/com/coders/laundry/service/TokenManagerService.java
  src/main/resources/mapper/searchHistoryMapper.xml
  src/test/java/com/coders/laundry/controller/SearchHistoryControllerTest.java
  src/test/java/com/coders/laundry/repository/SearchHistoryRepositoryTest.java
  src/test/java/com/coders/laundry/service/SearchHistoryServiceTest.java
Labels: enhancement, API

#1 Feature/activeMQ design
  build.gradle
  src/main/java/com/coders/laundry/client/activemq/MessageConsumer.java
  src/main/java/com/coders/laundry/client/activemq/MessageProducer.java
  src/main/java/com/coders/laundry/configuration/ActiveMQConfig.java
  src/main/java/com/coders/laundry/configuration/ObjectMapperConfig.java
  src/main/java/com/coders/laundry/controller/ActiveMQTestController.java
Labels: test, mq, developing

#11 Feature/separate config
  src/main/java/com/coders/laundry/configuration/ActiveMQConfig.java
  src/main/resources/application.yml
Labels: enhancement
